apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agent.name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.agent.name }}
    agentcert.io/managed: "true"
    agentcert.io/version: {{ .Values.agent.version | quote }}
  annotations:
    agentcert.io/vendor: {{ .Values.agent.vendor | quote }}
type: Opaque
stringData:
{{- range $key, $value := .Values.agent.secret }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
