{{- if or .Values.rbac.create .Values.rbac.cluster.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.agent.name }}-sa
  labels:
    app.kubernetes.io/name: {{ .Values.agent.name }}
{{- end }}
